// <auto-generated />
using System;
using Kemenkeu.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kemenkeu.Migrations
{
    [DbContext(typeof(KemenkeuContext))]
    [Migration("20190528225221_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kemenkeu.Models.Berita", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("DetailBerita")
                        .IsRequired()
                        .HasColumnName("Detail_Berita")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JudulBerita")
                        .IsRequired()
                        .HasColumnName("Judul_Berita")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("TanggalDiedit")
                        .HasColumnName("Tanggal_Diedit")
                        .HasColumnType("date");

                    b.Property<DateTime>("TanggalDitambahkan")
                        .HasColumnName("Tanggal_Ditambahkan")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Berita");
                });

            modelBuilder.Entity("Kemenkeu.Models.DetailProyek", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("DetailProyek1")
                        .IsRequired()
                        .HasColumnName("Detail_Proyek")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Detail_Proyek");
                });

            modelBuilder.Entity("Kemenkeu.Models.Pjpk", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("TanggalDiedit")
                        .HasColumnName("Tanggal_Diedit")
                        .HasColumnType("date");

                    b.Property<DateTime>("TanggalDitambahkan")
                        .HasColumnName("Tanggal_Ditambahkan")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("PJPK");
                });

            modelBuilder.Entity("Kemenkeu.Models.Proyek", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Fasilitas")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("NamaProyek")
                        .IsRequired()
                        .HasColumnName("Nama_Proyek")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("Nilai");

                    b.Property<string>("Pjpk")
                        .IsRequired()
                        .HasColumnName("PJPK")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Sektor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("TanggalDiedit")
                        .HasColumnName("Tanggal_Diedit")
                        .HasColumnType("date");

                    b.Property<DateTime>("TanggalDitambahkan")
                        .HasColumnName("Tanggal_Ditambahkan")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Proyek");
                });

            modelBuilder.Entity("Kemenkeu.Models.DetailProyek", b =>
                {
                    b.HasOne("Kemenkeu.Models.Proyek", "IdNavigation")
                        .WithOne("DetailProyek")
                        .HasForeignKey("Kemenkeu.Models.DetailProyek", "Id")
                        .HasConstraintName("FK_Detail_Proyek_Proyek");
                });
#pragma warning restore 612, 618
        }
    }
}
